# Generated by Django 4.0.6 on 2024-04-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0002_musicas_rename_ano_album_ano_lancamento_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musicas',
            new_name='Musica',
        ),
    ]
