# Generated by Django 4.0.6 on 2024-04-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_rename_musicas_musica'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='album_images/'),
        ),
    ]
