# Generated by Django 4.0.6 on 2024-04-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_album_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='imagem',
        ),
        migrations.AddField(
            model_name='album',
            name='imagem_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
