# Generated by Django 4.0.6 on 2024-04-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0005_remove_album_imagem_album_imagem_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='imagem_url',
        ),
        migrations.AddField(
            model_name='album',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='album_images/'),
        ),
    ]
