# Generated by Django 4.0.6 on 2024-06-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0007_banda_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banda',
            name='foto',
        ),
        migrations.AddField(
            model_name='banda',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='album_images/'),
        ),
    ]
