# Generated by Django 4.0.6 on 2024-06-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0009_remove_banda_imagem_banda_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='musica',
            name='letra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
