# Generated by Django 4.0.6 on 2024-04-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comen',
            old_name='titulo',
            new_name='comentario',
        ),
    ]
